apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-env
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/part-of: init-vue
    app.kubernetes.io/component: init-vue
data:
  config.js: |
    var config = {
        {{ if (.Values.Deployment.Env.plain) }}
          {{ range $envName, $envValue := .Values.Deployment.Env.plain }}
          {{ $envName | quote}} : {{ $envValue | quote}},
          {{ end }}
        {{ end }}
        "APP_VERSION" : "{{ .Values.Deployment.Image.tag }}"
      };
